----------------------------------------------------------------------------------------------------------------
-- Default Key Combo Bindings
-- (c) 2004 Relic Entertainment Inc.

-- These combos should NOT be changed by the user.
-- They are here in case the user screws up the key bindings file in Root/KeyBindings/

-- Bindings use format "Control+Shift+A"

-- Valid keys
	--  a - Z   0 - 9
	-- Backspace Tab Enter Escape Space Apostrophe Comma Minus Period Slash Semicolon Equal LBracket Backslash RBracket Grave 
	-- Up Down Left Right Control Shift Alt CapsLock NumLock ScrollLock Insert Delete Home End PageUp PageDown F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 PrintScreen Pause 
	-- MouseLeft MouseRight MouseMiddle MouseTop MouseBottom 
	-- ScreenLeft ScreenRight ScreenTop ScreenBottom 
	-- Numpad0 Numpad1 Numpad2 Numpad3 Numpad4 Numpad5 Numpad6 Numpad7 Numpad8 Numpad9 NumpadMultiply NumpadPlus NumpadSeparator NumpadMinus NumpadPeriod NumpadSlash 
	
bindings_version = 15.2
bindings_locstring = "$11271752"

--[[CHANGES SINCE VERSION 15.1
SPACE MARINES
- added a new binding "marine_librarian_research_2_w40k" to cover the Weaken Resolve research in the original campaign in which it is gated behind Word of the Emperor and shares that position.
]]


--[[
MODERN HOTKEY DESIGN:
GENERAL PRIORITIES:
1. Harmonize Hotkeys Across Factions
2. Where possible hotkeys for similar concepts harmonize (most melee items on Z for example)
3. Core Commands Close at Hand (favoring right hand)
4. With uniques, favor first letter

TASKBAR/CORE COMMANDS
	Move M
	Stop S
	Attack A
	Force Melee Z
	Build B
	Repair H
	Combat Stance Toggle Q
	Melee Stance Togger W
	Rally Point Period (.)
ADVANCED COMMANDS
	Cycle HQ F1
	Cycle Builder Grave (`)
	Cycle Idle Military F2
	Cycle Research F3
	Ping F7
	Toggle Ping Type F8
	Pause/Unpause Overwatch F9
	Cancel Overwatch F10
	Jump to Notification Space
	Hide Taskbar Ctrl+Space
	Direct to Combat Stances: NumPad 1-5
	Direct to Melee Stances: Numpad 7-8
	Lock Camera to Selection: Shift+Space
UNITS
	Infantry
		Light Infantry / Scouts: L
		Core Infantry I
		Mid-Tier Melee M
		Jump Units J
		Ranged Elites: R
		Melee Elites Z
	Hero Units
		Commander C
		Psyker/Caster Hero Y
		Healer Hero H
		Melee Tank Hero Z
	Vehicles
		Light/Recon L
		Walker W
		Transport T
		Heavy Tank H
		Artillery A
		Flyers F
		Super Unit S
BUILDINGS
	Barracks B
	Research R
	Vehicle Bay V
	Commander / Secondary Research C
	Tier 3 Building S
	Listening Post L
	Generator G
	Thermo Generator O
	Turret T
	Minefield M
RESEARCH/ADDONS
	Tier Upgrades and Similar U
	Requisition Upgrades on LPs R
	Health Upgrades H
	Ranged Damage/Accuracy R
	Commander Health/Veterancy C
	Melee Wargear Z
	Ranged Warger P
	(where possible upgrades that unlock an item have the same hotkey as thay item)
WEAPON UPGRADES
	Heavy Bolter, etc B
	Flamers B
	Plasma/Engergy P
	Grenade Launchers G
	Missile Launchers I
	Lascannons (for vehicles) L
	Turrets T
ABILITIES
	Grenades: G
	Other Damage: X
	Speed Boosts: F
	Traps/Ground Items: T
	Aura Cries/Buffs: B
	Debuffs: D
	Heal: H
	Infiltration: I
	Global Abiliies (Dark Eldar): [ ] \ ; ' /
]]


bindings =
{
	----------------------------------------------------------------------------------------------------------------
	-- SYSTEM COMMANDS
	----------------------------------------------------------------------------------------------------------------
	escape				= "Tab",
	accept				= "Enter",
	commandqueue		= "Shift",
	systemmenu			= "Escape",
	objectivesmenu		= "Control+O",
	alliesmenu			= "Control+D",
	chatmenu			= "Enter",
	chathistory			= "Shift+Enter",
	pause				= "Pause",
	selectionfocus      = "Shift+Space",
	
	----------------------------------------------------------------------------------------------------------------
	-- TASKBAR COMMANDS
	----------------------------------------------------------------------------------------------------------------
	stop 				= "S",
	move 				= "M",
	attackmove			= "A",
	attackmelee			= "Z",
	build				= "B",
	buildadv			= "",
	attach				= "C",
	attackground		= "G",
	rally				= "Period",
	combatstance		= "Q",
	meleestance			= "W",
	scuttle				= "Delete",
	unload				= "N",--
	deepstrike			= "E",--
	reinforce			= "R",
	leader				= "L",
	cancelconstruction 	= "Escape",
	-- These items appear as abilities to the player but are actually extensions	
	jump						= "J",
	infiltrate					= "I",
	rampage						= "R",
	repair						= "H",	
	possess						= "U",-- Bloodthirster and Daemon Prince
	relocate					= "J", --eldar building relocation
	cannibalism					= "H", -- kroot cannibalism
	possess_enemy				= "P", -- necron possession
	fear						= "F",
	tau_snare_trap				= "T", -- tau commander trap
	tau_holographic_projection	= "H", 
	direct_spawn				= "F",	--This spawns the attack scarabs (who are flyers)
	necron_stasis_field			= "F",
	necron_nightmare_shroud		= "O", -- also used for Khorne Berzerkers' "Mark of Khorne"
	entrench					= "E", -- IG Heavy Weapons Teams / Tau Broadsides
	burrow						= "B",
	lightning_field				= "L", -- Necron Lord
	direct_spawn_rally			= "Period",  --?
	melee_dance					= "D", -- Eldar Harlequin
	harvest						= "H", -- Necron Tomb Spyder
	
	----------------------------------------------------------------------------------------------------------------
	-- ADVANCED TASKBAR COMMANDS
	----------------------------------------------------------------------------------------------------------------
	hq_cycle				= "F1",
	military_cycle			= "F2",
	builder_cycle			= "Grave",
	research_cycle			= "F3",
	cycle_event_cue			= "Space",
	stance_hold				= "Numpad1",
	stance_stand_ground		= "Numpad2",
	stance_burn				= "Numpad3",
	stance_cease_fire		= "Numpad4",
	stance_attack			= "Numpad5",
	melee_stance_assault	= "Numpad7",
	melee_stance_ranged		= "Numpad8",
	toggle_taskbar			= "Control+Space",
	minimap_ping			= "F7",
	minimap_ping_toggle		= "F8",
	toggle_overwatch		= "F9",
	cancel_overwatch		= "F10",
	
	----------------------------------------------------------------------------------------------------------------
	-- MULTIPLE SELECTION HOTKEYS
	----------------------------------------------------------------------------------------------------------------
	focus_primary_selection 	= "Control+Tab",
	next_primary_selection  	= "Tab",
	prev_primary_selection  	= "Shift+Tab",
	remove_selection_modifier  	= "Control",		-- checked with mouse click (removes clicked items from selection) -- note: must only be one key
	crop_selection_modifier  	= "Shift",		-- checked with mouse click (selects all units of the same type) -- note: must only be one key
		
	----------------------------------------------------------------------------------------------------------------
	-- DATA CONTEXT HOTKEYS
	----------------------------------------------------------------------------------------------------------------
	
	-- BUILDINGS FOR MARINES
	marine_hq					= "H",
	marine_artefact				= "C",
	marine_armoury				= "R",
	marine_chapel				= "B",
	marine_generator			= "G",
	marine_listening_post		= "L",
	marine_orbital_relay		= "S",
	marine_temp_drop_building	= "D",
	marine_thermo_generator		= "O",
	marine_bolter_turret		= "T",
	marine_machine_cult			= "V",
	marine_mine_field			= "M",

	-- BUILDINGS FOR CHAOS 
	chaos_hq					= "H",
	chaos_sacrificial_circle	= "C",
	chaos_armoury				= "R",
	chaos_temple				= "B",
	chaos_generator				= "G",
	chaos_listening_post		= "L",
	chaos_greater_circle		= "S",
	chaos_thermo_generator		= "O",
	chaos_bolter_turret			= "T",
	chaos_machine_pit			= "V",
	chaos_mine_field			= "M",

	-- BUILDINGS FOR ORKS
	ork_hq						= "H",
	ork_waagh_banner			= "T",
	ork_pile_o_guns				= "R",
	ork_boy_hut					= "B",
	ork_generator				= "G",
	ork_listening_post			= "L",
	ork_big_generator			= "O",
	ork_mek_shop				= "V",
	ork_mine_field				= "M",

	-- BUILDINGS FOR ELDAR
	eldar_hq					= "H",
	eldar_aspect_portal			= "B",
	eldar_soul_shrine			= "R",
	eldar_webway_gate			= "W",--Unique
	eldar_generator				= "G",
	eldar_listening_post		= "L",
	eldar_advanced_generator	= "O",
	eldar_support_platform		= "T",
	eldar_support_portal		= "V",
	eldar_mine_field			= "M",

	-- BUILDINGS FOR TAU
	tau_barracks				= "B",
	tau_hq						= "H",
	tau_kroot_nest				= "N",--Unique
	tau_listening_post			= "L",
	tau_plasma_generator		= "G",
	tau_research_building		= "R",
	tau_shrine_of_kauyon		= "K",--Unique
	tau_shrine_of_montka		= "M",--Unique
	tau_shrine_of_purpose		= "S",
	tau_thermo_generator		= "O",
	tau_vehicle_building		= "V",

	-- BUILDINGS FOR NECRONS
	necron_energy_core				= "S",
	necron_forbidden_archive		= "C",
	necron_greater_summoning_core	= "V",
	necron_listening_post			= "L",
	necron_monolith					= "H",
	necron_plasma_generator			= "G",
	necron_summoning_core			= "B",
	necron_thermo_generator			= "O",
	necron_turret					= "T",
	
    	-- BUILDINGS FOR IMPERIAL GUARD
	guard_hq					= "H",
	guard_tactica				= "R",
	guard_infantry				= "B",
	guard_generator				= "G",
	guard_listening_post		= "L",
	guard_mars_command			= "S",
	guard_thermo_generator		= "O",
	guard_bolter_turret			= "T",
	guard_mechanized_command 	= "V",
	guard_mine_field 			= "M",
	
	-- BUILDINGS FOR DARK ELDAR
	dark_eldar_hq						= "H",
	dark_eldar_haemonculus_laboratory	= "R",
	dark_eldar_hall_of_blood			= "B",
	dark_eldar_dark_foundry				= "V",
	dark_eldar_generator				= "G",
	dark_eldar_listening_post			= "L",
	dark_eldar_slave_caravel			= "A",--Unique
	dark_eldar_soul_cage				= "S",
	dark_eldar_thermo_generator			= "O",
	dark_eldar_wych_cult_arena			= "C",

	-- BUILDINGS FOR SISTERS
	sisters_hq					= "H",
	sisters_infantry			= "B",
	sisters_sanctuary			= "R",
	sisters_generator			= "G",
	sisters_thermo_generator	= "O",
	sisters_listening_post		= "L",
	sisters_vehicle_building	= "V",
	sisters_turret_flamer		= "T",
	sisters_holy_reliquary		= "C",
	sisters_shrine				= "S",
	sisters_mines				= "M",

	-- TROOPERS FOR MARINES
	marine_servitor				= "B",
	marine_dreadnought			= "W",
	marine_dreadnought_hellfire	= "D",
	marine_force_commander		= "C",
	marine_chaplain				= "Z",
	marine_grey_knights			= "M",
	marine_land_speeder			= "L",
	marine_librarian			= "Y",
	marine_skull_probe			= "P",
	marine_scout				= "L",
	marine_apothecary			= "H",
	marine_assault_marine		= "J",
	marine_sergeant				= "",
	marine_space_marine			= "I",
	marine_terminator			= "R",
	marine_assault_terminator	= "Z",	
	marine_land_raider			= "S",
	marine_predator				= "H",
	marine_rhino				= "T",
	marine_whirlwind			= "A",
	marine_techmarine			= "",
	marine_tempest				= "F",


	-- TROOPERS FOR CHAOS
	chaos_bloodthirster			= "S",
	chaos_cultist				= "L",
	chaos_daemon_prince			= "C",
	chaos_defiler				= "W",
	chaos_horrors				= "A", --
	chaos_lord					= "C",
	chaos_marines				= "I",
	chaos_raptors				= "J",
	chaos_possessed				= "Z",
	chaos_obliterator			= "R",
	chaos_predator				= "H",
	chaos_aspiring_champion		= "L",
	chaos_rhino					= "T",
	chaos_heretic				= "B",
	chaos_sorcerer				= "Y",
	chaos_khorne_berserker		= "M",
	chaos_dreadnought			= "",
	chaos_hell_talon			= "F",


	-- TROOPERS FOR ORKS
	ork_flash_gitz				= "R",
	ork_nobs					= "M",
	ork_shoota_boyz				= "I",
	ork_slugga_boyz				= "L",
	ork_stormboyz				= "J",
	ork_tankbustas				= "A",
	ork_grots					= "B",
	ork_killa_kan				= "W",
	ork_bad_dok					= "H",
	ork_mek_boy					= "Y",
	ork_nob_leader				= "L",
	ork_warboss					= "C",
	ork_looted_tank				= "H",
	ork_squiggoth				= "S",
	ork_trukk					= "T",	
	ork_wartrak					= "L",
	ork_armored_nob				= "Z",
	ork_gun_wagon				= "",
	ork_fighta_bomma			= "F",
	
	-- TROOPERS FOR ELDAR
	eldar_bonesinger				= "B",
	eldar_grav_platform_laser		= "S",--unique
	eldar_grav_platform_brightlance	= "B",--unique
	eldar_avatar					= "S",
	eldar_farseer					= "C",
	eldar_harlequin					= "Z",
	eldar_warlock					= "L",
	eldar_warlock_seer				= "Y",
	eldar_falcon_grav_tank			= "T",
	eldar_fire_prism				= "H",
	eldar_vyper						= "L",
	eldar_wraithlord				= "W",
	eldar_banshee					= "M",
	eldar_banshee_exarch			= "M",
	eldar_dark_reapers				= "R",	
	eldar_dark_reaper_exarch		= "R",
	eldar_guardians					= "I",
	eldar_rangers					= "L",
	eldar_warp_spiders				= "J",		
	eldar_warp_spiders_exarch		= "J",		
	eldar_fire_dragon				= "A",	
	eldar_wraithguard				= "",
	eldar_nightwing					= "F",


	-- TROOPERS FOR TAU
	tau_attack_drone				= "A",--Unique
	tau_broadside_battlesuit		= "R",
	tau_builder						= "B",
	tau_centaur_auxiliary			= "",
	tau_commander					= "C",
	tau_commander_shield_drone		= "D",
	tau_commander_sp_drone			= "G",
	tau_crisis_suit					= "J",
	tau_devilfish_carrier			= "T",
	tau_drone_harbinger				= "R",--Unique
	tau_drone_squad					= "D",--Unique
	tau_energy_auxiliary			= "",
	tau_eradicator					= "",
	tau_eradicator_kroot			= "",
	tau_ethereal					= "Y",
	tau_eviscerator					= "",
	tau_eviscerator_kroot			= "",
	tau_fire_warrior				= "I",
	tau_fire_warrior_shasui			= "L",
	tau_fire_warrior_shield_drone	= "D",--Unique
	tau_glob_auxiliary				= "",
	tau_greater_knarloc				= "S",
	tau_hammerhead					= "H",
	tau_kroot_hound					= "Z",
	tau_kroot_shaper				= "H",
	tau_kroot_warrior				= "M",
	tau_krootox						= "W",
	tau_pathfinder					= "P",--Unique
	tau_skyray						= "A",
	tau_stealth_warrior				= "L",
	tau_vespid_auxiliary			= "Z",
	tau_piranha						= "",
	tau_barracuda					= "F",
	
	-- TROOPERS FOR NECRONS
	necron_attack_scarab			= "F",
	necron_builder_scarab			= "B",
	necron_destroyer				= "L",
	necron_flayed_one				= "M",
	necron_heavy_destroyer			= "H",
	necron_immortal					= "R",	
	necron_lord						= "C",
	necron_lord_destroyer			= "A",
	necron_pariah					= "Z",
	necron_restored_monolith		= "U",--Unique
	necron_tomb_spyder				= "T",
	necron_warrior					= "I",
	necron_wraith					= "J",
	necron_deceiver					= "",

	-- TROOPERS FOR IMPERIAL GUARD
	guard_enginseer				= "B",
	guard_guardsmen				= "I",
	guard_heavy_weapon			= "R",
	guard_command_squad			= "C",
	guard_commissar				= "H",
	guard_commissar_command		= "H",
	guard_priest				= "Z",
	guard_priest_command		= "P",-- Normal Z coflicts when he's a leader option in command squad
   	guard_psyker				= "Y",
   	guard_psyker_command		= "Y",
	guard_kasrkin				= "K",--Unique
	guard_kasrkin_bodyguard		= "K",--Unique
	guard_ogryn					= "Z",
	guard_basilisk				= "A",
	guard_sentinel				= "W",
	guard_hellhound				= "L",
	guard_assassin				= "A",--Unique
	guard_baneblade				= "S",
	guard_leman_russ			= "H",
	guard_chimera				= "T",
	guard_sergeant				= "L",
	guard_demolisher			= "",
	guard_marauder				= "F",

	
	-- TROOPERS FOR DARK ELDAR
	dark_eldar_slave			= "B",
	dark_eldar_mandrake			= "L",
	dark_eldar_archon			= "C",
	dark_eldar_incubus			= "L",
	dark_eldar_warrior			= "I",
	dark_eldar_hellion			= "J",
	dark_eldar_scourge			= "R",
	dark_eldar_warp_beast		= "Z",
	dark_eldar_wych				= "M",
	dark_eldar_haemonculus		= "H",
	dark_eldar_reaver			= "L",
	dark_eldar_raider			= "T",
	dark_eldar_talos			= "W",
	dark_eldar_ravager			= "H",
	dark_eldar_dais				= "S",
	dark_eldar_squad_leader		= "L",
	dark_eldar_murdered_slave	= "D",--Unique
	dark_eldar_raven			= "F",


	-- TROOPERS FOR SISTERS
	sisters_servitor					= "B",
	sisters_battle_sister				= "I",
	sisters_seraphim					= "J",
	sisters_repentia					= "M",
	sisters_celestian					= "R",
	sisters_missionary					= "H",
	sisters_assassin					= "Z",
	sisters_canoness					= "C",
	sisters_confessor					= "Y",
	sisters_celestian_imagifer			= "F",--Unique
	sisters_repentia_mistress			= "L",
	sisters_veteran_superior			= "L",
	sisters_veteran_superior_celestian	= "L",
	sisters_veteran_superior_seraphim	= "L",
	sisters_living_saint				= "S",
	sisters_exorcist_tank				= "A",
	sisters_immolator_tank				= "H",
	sisters_penitent_engine				= "W",
	sisters_rhino						= "T",
	sisters_lightning					= "F",

	-- WEAPON UPGRADES FOR MARINES
	marine_assault_cannon			= "C",
	marine_flamer					= "F",
	marine_heavy_flamer				= "F",
	marine_heavy_bolter				= "B",
	marine_lascannon_1				= "L",
	marine_lascannon_2				= "L",
	marine_lascannon_twin			= "T",
	marine_missile_launcher			= "I",
	marine_plasma_gun				= "P",
	marine_sniper_rifle				= "N",
	marine_missile_launcher_turret	= "U",
	marine_power_halberd			= "",
	marine_missile_frag				= "F",
	marine_missile_krak				= "K",


	-- WEAPON UPGRADES FOR CHAOS 	
	chaos_flamer					= "F",
	chaos_heavy_flamer				= "F",
	chaos_grenade_launcher			= "G",
	chaos_heavy_bolter				= "B",
	chaos_lascannon_1				= "L",
	chaos_lascannon_2				= "L",
	chaos_lascannon_twin			= "T",
	chaos_missile_launcher			= "I",
	chaos_plasma_gun				= "P",
	chaos_missile_launcher_turret	= "U",
	chaos_multi_melta				= "",
	
	-- WEAPON UPGRADES FOR ORKS
	ork_big_shoota					= "B",
	ork_kustom_shoota				= "B",
	ork_bomb_chucka					= "C",
	ork_burna						= "F",
	ork_mega_blasta					= "B",
	ork_power_klaw					= "K", --Unique
	ork_rokkit_launcha				= "I",
	ork_rokkit_launcha_twin			= "T",
	ork_shoota						= "B",
	ork_zzzap_gun					= "P",
		
	-- WEAPON UPGRADES FOR GUARD
	guard_grenade_launcher				= "G",
	guard_plasma_gun					= "P",
	guard_lasgun_heavy_weapons_team 	= "L",
	guard_autocannon_heavy_weapons_team	= "C",
	guard_multi_melta					= "",
	guard_multi_laser_sentinel			= "L",
	guard_autocannon_sentinel			= "C",

	-- WEAPON UPGRADES FOR ELDAR
	eldar_bright_lance				= "L",
	eldar_dcannon					= "C",
	eldar_missile_launcher			= "I",
	eldar_scatter_laser				= "L",
	eldar_shuriken_cannon			= "B",
	eldar_starcannon				= "C",
	eldar_witchblade_seercouncil	= "B",

	-- WEAPON UPGRADES FOR TAU
	tau_flamer_commander				= "F",
	tau_missile_launcher_commander		= "I",
	tau_plasma_rifle_commander			= "P",
	tau_missile_launcher_crisis_suit	= "I",
	tau_flamer_crisis_suit				= "F",
	tau_stealth_suit_fusion_blaster		= "P",
	
	-- WEAPON UPGRADES FOR NECRONS	
	necron_tomb_spyder_particle_projector	= "L",
	
-- WEAPON UPGRADES FOR DARK ELDAR
	dark_eldar_darklance_raider			= "D",
	dark_eldar_darklance_scourge		= "D",
	dark_eldar_disintegrator_ravager	= "C",

	--WEAPON UPGRADES FOR SISTERS
	sisters_flamer				= "F",
	sisters_heavy_bolter		= "B",
	sisters_chainsword			= "C",
	sisters_multi_melta			= "I",
	sisters_meltagun			= "P",

	-- RESEARCH FOR MARINES
	marine_accuracy_research_1					= "R",
	marine_accuracy_research_2					= "R",
	marine_force_commander_research_1			= "B",
	marine_force_commander_research_2			= "B",
	marine_daemon_hammer_research				= "",
	marine_frag_grenade_research				= "G",
	marine_health_research_1					= "H",
	marine_health_research_2					= "H",
   	marine_commander_health_research_1			= "C",
	marine_commander_health_research_2			= "C",
	marine_librarian_research_1					= "O", --word of the emperor
	marine_librarian_research_2					= "D", --weaken resolve
	marine_librarian_research_2_w40k			= "D", -- variant for original campaign where research is in different position	marine_max_weapons_research					= "W",
	marine_melta_bomb_research					= "K",
	marine_power_research_1						= "U",
	marine_power_research_2						= "U",	
	marine_requisition_research_1				= "R",
	marine_requisition_research_2				= "R",
	marine_scout_infiltration_research			= "I",
	marine_sniper_rifle_research				= "N",
	marine_smoke_launcher_research				= "G",	
	marine_squad_cap_research					= "S",		
	marine_vehicle_cap_research					= "V",
	marine__melee_research_1					= "Z",
	marine_sergeant_melee_research_2			= "Z",		
	marine_sergeant_ranged_research				= "P",
	marine_personalteleporter_research			= "J",
	marine_heavy_armor_deployment				= "U",
	marine_furious_charge_research				= "F",
	marine_power_swords_research				= "Z",
	marine_skull_probe_infiltration_research 	= "P",
	
	-- RESEARCH FOR CHAOS
	-- HQ
	chaos_squad_cap_research		= "S",		
	chaos_vehicle_cap_research		= "V",		
	-- BARRACKS
	chaos_cultist_sight_research	= "D",
	chaos_frag_grenade_research		= "G",
	chaos_raptor_speed_research		= "B",
	-- ARMORY
	chaos_furious_charge_research		= "F",	
	chaos_purge_the_weak				= "H",
	chaos_max_weapons_research			= "W",
	chaos_rage_research					= "B",--MARK OF KHORNE
	chaos_champion_melee_research_1		= "Z",
	chaos_champion_melee_research_2		= "Z",		
	chaos_champion_ranged_research		= "P",	
	chaos_infiltration_research			= "I",
	chaos_marine_infiltration_research	= "M",
	-- VEHICLE
	chaos_smoke_launcher_research		= "S",		
	chaos_projectiles 					= "U",
	-- COMMANDER
	chaos_possessed_daemon_fire_research	= "F",
	chaos_commander_health_research_1		= "C",
	chaos_commander_health_research_2		= "C",
	chaos_lord_research_1					= "B",--SYMBOL OF CHAOS
	chaos_lord_research_2					= "B",--DAEMON STR
	chaos_sorcerer_research_1				= "Y",
	chaos_sorcerer_research_2				= "Y",
	-- OTHER
	chaos_power_research_1					= "U",
	chaos_power_research_2					= "U",	
	chaos_requisition_research_1			= "R",
	chaos_requisition_research_2			= "R",
	chaos_personalteleporters				= "J",
	chaos_bloodthirster_research			= "S",
	chaos_daemon_prince_research			= "D",
	
	chaos_ranged_research_1						= "R",
	chaos_health_research_1						= "H",
	chaos_health_research_2						= "H",
	chaos_accuracy_upgrade_research_1			= "R",
	chaos_accuracy_upgrade_research_2			= "R",
	chaos_possessed_daemon_flight_research 		= "A",
	chaos_possessed_daemon_mutation_research	= "M",
	chaos_possessed_daemon_talons_research 		= "T",


	-- RESEARCH FOR ORKS
	--HQ
	ork_research_grot_infiltration 				= "I",
	ork_tankbusta_infiltration_research			= "T",
	--BARRACKS
	ork_kustom_force_field_research				= "K",--KUSTOM GADJITS
	--ARMORY
	ork_moredakka_research_1					= "R",
	ork_moredakka_research_2					= "R",
	ork_moreshooty_research_1					= "I",
	ork_moreshooty_research_2					= "I",
	ork_big_shoota_research						= "I",
	ork_burna_research							= "F",
	ork_warboss_ranged_research					= "P",	
	ork_morechoppy_research_1					= "Z",
	ork_morechoppy_research_2					= "Z",
	ork_eavy_armour_research					= "H",
	ork_eavy_armor_boyz_research				= "H",
	ork_tougherbosses_research_1				= "C",
	ork_tougherbosses_research_2				= "C",
	ork_research_more_sluggas					= "L",
	ork_speed_boost_stormboyz_research			= "J",
	--VEHICLE
	ork_extra_armour_research					= "U",
	ork_speed_boost_research					= "V",
	--OTHER
	ork_power_research_1						= "U",
	ork_power_research_2						= "U",
	ork_requisition_research_1					= "R",
	ork_requisition_research_2					= "R",
	
	ork_big_squad_research						= "B",
	ork_mega_blasta_research					= "M",
	ork_mekboy_melee_research					= "M",
	ork_mekboy_ranged_research					= "R",
	ork_powerclaw_research						= "O",	
	ork_rokkit_research							= "I",
	ork_tougherorks_research_1					= "T",
	ork_tougherorks_research_2					= "T",
	ork_tankbustin_kit_research					= "A",
	ork_kustom_tellyporta_research				= "J",
	ork_waaaaagh_research						= "",
	ork_research_stikk_bombs					= "G",
	ork_research_tankbustabombs 				= "M",

	-- RESEARCH FOR ELDAR
	--HQ
	eldar_bonesinger_ability_research_3	= "D",--WRAITHTOMB
	eldar_fleet_of_foot_research 		= "F",
	eldar_plasma_grenade_research 		= "G",
	eldar_warlock_ability_research_1	= "M",--MYSTICISM
	eldar_tier2_research 				= "U",
	--BARRACKS
	eldar_ranger_infiltration_research 	= "I",
	eldar_haywire_grenade_research 		= "W", --WARP SPIDER EQUIPMENT
	--ARMORY
	eldar_annihilate_the_enemy			= "U",
	eldar_farseer_ability_research_1	= "F",--FORTUNE
	eldar_farseer_ability_research_3	= "E", -- ELDRITCH STORM
	eldar_exarch_ability_research_1		= "M",
	eldar_research_infantryaccuracy_1	= "R",
	eldar_research_infantryaccuracy_2	= "R",
	eldar_researchinfantryhealth_1		= "H",
	eldar_researchinfantryhealth_2		= "H",
	eldar_research_farseerhealth_1		= "C",
	eldar_research_farseerhealth_2		= "C",
	--VEHICLE
	eldar_vehicle_ability_research		= "V", --VEHICLE HOLO-FIELD
	eldar_nightwing_regen_research 		= "N",--NIGHTWING REGEN
	--OTHER
	eldar_power_research_1 					= "U",
	eldar_power_research_2 					= "U",
	eldar_requisition_research_1 			= "R",
	eldar_requisition_research_2 			= "R",
	eldar_health_research					= "H",
	eldar_webway_gate_relocation_research	= "R",
	eldar_shroud_ability_research			= "I",
	
	eldar_ability_research				= "A",
	eldar_accuracy_research				= "A",
	eldar_exarch_ability_research_2		= "O",
	eldar_farseer_ability_research_2	= "S",
	eldar_warlock_ability_research_2	= "E",
	eldar_warlock_ability_research_3	= "W",
	webway_gate_healing_research 		= "H",
	eldar_bonesinger_ability_research_1	= "T",

	-- RESEARCH FOR TAU
	tau_power_research_1			= "U",
	tau_power_research_2			= "U",
	tau_requisition_research_1		= "R",
	tau_requisition_research_2		= "R",
	tau_teachings_of_kauyon			= "U",
	tau_teachings_of_montka			= "U",
	tau_target_lock					= "L",
	tau_advanced_pulse_rifles		= "R",
	tau_improved_metallurgy			= "H",
	tau_targeting_optics			= "T",
	tau_missile_barrage				= "A",
	tau_feral_leap					= "Z",
	tau_jetpacks					= "J",
	tau_burst_cannon_enhancements	= "R",
	
	
	-- RESEARCH FOR NECRONS
	necron_power_research_1						= "U",
	necron_power_research_2						= "U",
	necron_chronometron_research				= "C",
	necron_lightning_field_research				= "L",
	necron_nightmare_shroud_research			= "O",
	necron_phase_shifter_research				= "H",
	necron_phalactery_research					= "Y",
	necron_resurrection_orb_research			= "R",
	necron_solar_pulse_research					= "P",
	necron_veil_of_darkness_research			= "I",
	necron_wraith_flight_research				= "W",
	necron_warrior_disruption_field_research	= "H",
	necron_nightbringer_research				= "N",
	necron_deceiver_research					= "D",
	necron_ctan_research						= "C",
	
	
	-- RESEARCH FOR GUARD
	--HQ
	--BARRACKS
	--ARMORY
	guard_guardsman_morale						= "M", -- DEATH BEFORE..
	guard_upgrade_guardsmen_health				= "H",
	guard_research_command_squad_size			= "C",
	guard_upgrade_guardsmen_range				= "R",
	guard_guardsman_morale_2					= "O", -- WILL OF THE EMPEROR..
	guard_upgrade_weapon_specialization			= "W",
	guard_research_kasrkin_speed				= "F",
	guard_research_kasrkin_armor				= "K",
	guard_upgrade_ogryn_melee					= "Z",
	guard_research_assassin_infiltrate			= "I",
	--VEHICLE
	--OTHER
	guard_upgrade_power_1						= "U",
	guard_upgrade_power_2						= "U",
	guard_upgrade_requisition_1					= "R",
	guard_upgrade_requisition_2					= "R",
	guard_full_scale_war 						= "U",
	guard_research_sentinel_armor				= "S",
	
-- RESEARCH FOR DARK ELDAR
	--HQ
	--BARRACKS
	dark_eldar_research_infiltration_mandrake		= "N",
	--RESEARCH
	dark_eldar_upgrade_retinue						= "C",
	dark_eldar_research_daemonic_touch				= "L",
	dark_eldar_upgrade_infantry_health				= "H",
	dark_eldar_research_poisoned_blades				= "B", --POISON BLADES
	dark_eldar_upgrade_soulseeker					= "R",
	dark_eldar_upgrade_destructor					= "P",
	dark_eldar_upgrade_power_scythe					= "Z",
	dark_eldar_upgrade_agonizer						= "Z",
	--VEHICLE
	dark_eldar_upgrade_vehicle_armor				= "V",
	dark_eldar_research_reaver_targeting			= "R",
	dark_eldar_research_wildfire					= "X",
	--OTHER
	dark_eldar_upgrade_commander_health				= "C",
	dark_eldar_research_crucible					= "R",
	dark_eldar_research_stinger						= "G",
	
	dark_eldar_research_gruesome_display			= "G",
	dark_eldar_research_short_circuit				= "C",
	dark_eldar_research_soulharvest					= "G",
	dark_eldar_research_terrorfex_grenade			= "T",
	dark_eldar_research_scythes						= "C",
	dark_eldar_research_soul_destruction			= "U",
	dark_eldar_research_talisman_of_petrification	= "E",
	dark_eldar_research_barbed_walls				= "B",
	dark_eldar_research_range_increase				= "R",
	dark_eldar_upgrade_power_1						= "U",
	dark_eldar_upgrade_power_2						= "U",
	dark_eldar_upgrade_requisition_1				= "R",
	dark_eldar_upgrade_requisition_2				= "R",


	-- RESEARCH FOR SISTERS
	--HQ
	sisters_research_emperors_touch				= "T", -- conflicts with builder
	sisters_research_divine_retribution			= "R", -- conflicts wiht laud hailer ability
	--BARRACKS
	sisters_squad_cap						= "S",
	sisters_research_phosphor_grenades		= "G",
	sisters_research_krak_grenades			= "K",
	--RESEARCH
	sisters_research_max_weapons			= "W",
	sisters_research_zealot_charge			= "F",
	sisters_research_blessed_ammunition		= "B",
	sisters_research_health					= "H",
	sisters_research_ranged_damage			= "R",
	sisters_research_leader_melee_1			= "Z",
	sisters_research_leader_melee_2			= "Z",
	sisters_research_leader_range			= "P",
	sisters_research_laud_hailer			= "D",
	--VEHICLE
	sisters_vehicle_cap						= "V",
	sisters_research_conflagration			= "F",
	sisters_research_holy_promethium		= "P",
	sisters_research_vehicle_armor			= "H",
	--OTHER
	sisters_research_commander_health_1		= "C",
	sisters_research_commander_health_2		= "C",
	sisters_research_divine_pronouncement	= "D",--
	sisters_research_ascension				= "O",--
	sisters_research_martyrs_gift			= "G",
	sisters_research_faithful_morale		= "M",
	sisters_upgrade_heart_of_worship		= "M",
	sisters_upgrade_power_1					= "U",
	sisters_upgrade_power_2					= "U",
	sisters_upgrade_requisition_1			= "R",
	sisters_upgrade_requisition_2			= "R",
	
	sisters_research_lay_hands				= "",
	sisters_research_battle_standard		= "",
	
	-- ADDONS FOR MARINES
	marine_hq_addon_1			= "U",
	marine_hq_addon_2			= "U",
	marine_listening_post_1		= "U",
	marine_listening_post_2		= "U",
	marine_turret_addon			= "U",
	
	-- ADDONS FOR CHAOS
	chaos_hq_addon_1					= "U",
	chaos_hq_addon_2					= "U",
	chaos_listening_post_1				= "U",
	chaos_listening_post_2				= "U",
	chaos_turret_addon					= "U",
		
	-- ADDONS FOR ELDAR
	eldar_banshee_aspect_stone		= "M",
	eldar_dark_reaper_aspect_stone	= "R",
	eldar_fire_prism_aspect_stone	= "H",
	eldar_fire_dragon_aspect_stone	= "A",
	eldar_vyper_aspect_stone		= "L",
	eldar_warp_spider_aspect_stone	= "J",
	eldar_wraithlord_aspect_stone	= "W",
	eldar_support_platform_addon	= "U",
	eldar_listening_post_1			= "U",
	eldar_listening_post_2			= "U",
	eldar_wraithguard_aspect_stone	= "G",

	-- ADDONS FOR TAU
	addon_tau_hq_1					= "",
	addon_tau_list_post_1			= "U",
	addon_tau_list_post_2			= "U",

	-- ADDONS FOR NECRONS
	addon_necron_turret				= "U",
	addon_necron_list_post_1		= "U",
	addon_necron_list_post_2		= "U",
	addon_necron_hq_1				= "U",
	addon_necron_hq_2				= "U",
	
	-- ADDONS FOR ORKS
	ork_hq_addon					= "U",
	ork_waagh_banner_gunz_1			= "U",
	ork_waagh_banner_gunz_2			= "U",
	ork_waagh_banner_orkcap			= "U",
	ork_waagh_banner_popgrowth		= "U",
	ork_waagh_banner_supportgrowth	= "U",	
	ork_listening_post_1			= "U",
	ork_listening_post_2			= "U",

	-- ADDONS FOR IMPERIAL GUARD
	addon_guard_basilisk_depot		= "A",
	addon_guard_heavy_weapon_vault	= "",
	addon_guard_hellhound_depot		= "L",
	addon_guard_hq_1				= "U",
	addon_guard_hq_2				= "U",
	addon_guard_kasrkin_quarters	= "K",
	addon_guard_leman_russ_depot	= "H",
	addon_guard_list_post_1			= "U",
	addon_guard_list_post_2			= "U",
	addon_guard_ministorum_temple	= "P",
	addon_guard_ogryn_quarters		= "Z",
	addon_guard_sentinel_depot		= "W",
	addon_guard_telepathica_temple	= "Y",
	addon_guard_vindicare_temple	= "A",
	guard_turret_addon				= "U",
	addon_guard_demolisher_depot	= "D",

-- ADDONS FOR DARK ELDAR
	addon_dark_eldar_hq_upgrade				= "U",
	addon_dark_eldar_slave_graveyard		= "T", -- TORTURE PIT
	dark_eldar_gruesome_display				= "G",
	addon_dark_eldar_list_post_1			= "U",
	addon_dark_eldar_list_post_2			= "U",
	addon_dark_eldar_list_post_dark_lance	= "L",

	addon_dark_eldar_piercing_vision		= "",
	addon_dark_eldar_rend_soul				= "",
	addon_dark_eldar_sadism					= "",
	addon_dark_eldar_penumbra				= "",
	addon_dark_eldar_nights_veil			= "",
	addon_dark_eldar_screams_of_the_damned	= "",
	addon_dark_eldar_sudden_strike			= "",


	-- ADDONS FOR SISTERS
	addon_sisters_list_post_1	= "U",
	addon_sisters_list_post_2	= "U",
	addon_sisters_holy_icon		= "H",
	addon_sisters_hq_1			= "U",
	addon_sisters_hq_2			= "U",
	addon_sisters_turret		= "U",
	
	-- ABILITIES FOR MARINES
	
	marine_battlecry					= "B",
	marine_demoralize					= "D",
	marine_frag_grenades				= "G",
	marine_machine_spirit				= "B",
	marine_melta_bombs					= "G",
	marine_orbital_bombardment			= "X",
	marine_rally						= "Y", -- can't be standard B as will clash when leaders attach
	marine_sabotage						= "D",
	marine_smite						= "X",
	marine_smoke_launchers				= "G",
	marine_weaken_resolve				= "D",
	marine_word_of_emperer				= "B",
	marine_inquisition					= "X",
	marine_blessing_of_the_omnissiah	= "H",
	
	-- ABILITIES FOR CHAOS
	chaos_chains			= "D",
	chaos_corruption		= "T", 
	chaos_daemon_strength	= "B",
	chaos_daemon_roar		= "D",
	chaos_doom_bolt			= "X",
	chaos_force_labor		= "F",
	chaos_frag_grenades		= "G",	
	chaos_furious_rage		= "B",
	chaos_smoke_launchers	= "G",
	chaos_speed_fiends		= "E", -- overlaps with Flamer upgrade
	chaos_tainted_auspex	= "T",
	chaos_rage				= "",
	chaos_blood_rage		= "",
	chaos_biotoxin			= "X",

	-- ABILITIES FOR ELDAR
	eldar_bonesong				= "O",--
	eldar_eldritch_storm		= "E",-- overlaps with psychic storm
	eldar_psychic_storm			= "T",
	eldar_embolden				= "B",
	eldar_entanglement			= "D",
	eldar_fleetoffoot			= "F",	
	eldar_fortune				= "O", -- overlaps with embolden
	eldar_graviticboost			= "F",
	eldar_haywire_bombs			= "G",
	eldar_guide					= "U", -- overlaps with plas grenade 
	eldar_mind_war				= "X",
	eldar_plasma_grenades		= "G",
	eldar_warshout				= "D",
	eldar_wraithtomb			= "D",	
	eldar_shroud_ability		= "I",
	eldar_harlequin_kiss		= "X",
	eldar_soulstone				= "H",--

	-- ABILITIES FOR TAU
	tau_devour				= "D",
	tau_hamstring			= "",
	tau_sonic_pulse			= "B",
	tau_target_acquired		= "X",
	tau_mark_squad	        = "D",
	tau_emp_grenade			= "G",
	tau_photon_grenade      = "G",
	tau_missile_barrage		= "X",
	tau_canabalism			= "C",
	tau_entrench			= "E",
	tau_ion_shield			= "B",

	-- ABILITIES FOR NECRONS
	necron_phase_shifter		= "H",
	necron_solar_pulse			= "P",
	necron_chronometron			= "C",
	necron_mass_resurrection  	= "R",
	necron_possess_nightbringer	= "N",
	necron_possess_deceiver		= "D",

	necron_doom					= "X",
	necron_deceive				= "D",
	necron_grand_illusion		= "I",
	necron_misdirect			= "",
	
	-- ABILITIES FOR ORKS
	ork_fightabomba_strafe		= "X",
	ork_fightin_juice			= "B",
	ork_gimme_boyz_mek			= "",
	ork_gimme_boyz_warboss		= "",
	ork_pop_growth				= "",
	ork_power_of_waagh			= "B",	
	ork_stikkbombs				= "G",
	ork_tankbusta_bombs			= "G",
	ork_superstik_bomb			= "G",
	ork_turbo_boost				= "F",
	ork_waaaaagh				= "B",
	ork_tank_zzappa				= "D",
	ork_power_surge				= "F",

	-- ABILITIES FOR IMPERIAL GUARD
	guard_assassin_assassinate		= "B",
	earthshaker_round				= "X",
	guard_commissar_execute			= "E",
	guard_kasrkin_frag_grenades		= "F", -- conflicts with grenade launcher
	guard_priest_fanatical			= "B",
	guard_psyker_lighting_arc		= "X",
	guard_psyker_strip_soul			= "D",
	guard_strafing_run				= "T",
	guard_let_it_burn				= "T",
	guard_long_range_scanner		= "T",
	guard_curse_of_the_machine		= "V", -- conflicts with strip soul
	
	guard_incendiary_bombs			= "I",--
	guard_emp_bombs					= "E",--
	guard_smoke_bombs				= "O",--
	guard_krak_bombs				= "K",--

	-- ABILITIES FOR DARK ELDAR
	-- globals
	dark_eldar_piercing_vision			= "LBracket",
	dark_eldar_screams_of_the_damned	= "RBracket",
	dark_eldar_rend_soul				= "Backslash",
	dark_eldar_corrosion				= "Semicolon",
	dark_eldar_rekindle_rage			= "Apostrophe",
	dark_eldar_soulstorm				= "Slash",
	
	-- other
	dark_eldar_animus_vitae					= "G",
	dark_eldar_combat_drugs					= "B",
	dark_eldar_crucible						= "D",
	dark_eldar_darklance_sweep				= "X",
	dark_eldar_execute_slave				= "",--
	dark_eldar_talisman_of_petrification	= "D",
	dark_eldar_horrorfex					= "G",
	dark_eldar_short_circuit				= "D",
	dark_eldar_stinger						= "G",
	dark_eldar_tame_warp_beasts				= "B",
	dark_eldar_terrorfex					= "G",
	dark_eldar_torture_amp					= "T",
	dark_eldar_wildfire						= "X",
	dark_eldar_soul_shock					= "X",
	dark_eldar_tracking_device				= "G",
	dark_eldar_soul_destruction				= "X",
	dark_eldar_haywire_bombs				= "G",
	dark_eldar_war_frenzy					= "F",--
	dark_eldar_harvest_souls				= "V",


	-- ABILITIES FOR SISTERS
	sisters_dismantle				= "X",
	sisters_ascension				= "O",
	sisters_divine_light			= "D",
	sisters_divine_retribution		= "D",
	sisters_emperors_touch			= "T",
	sisters_holy_passion			= "F",--
	sisters_ardent_flame			= "X",
	sisters_battle_standard			= "",--
	sisters_lay_hands				= "H",
	sisters_conflagration			= "X",
	sisters_divine_pronouncement	= "D",
	sisters_hk_missiles				= "X",
	sisters_holy_rage				= "F",--
	sisters_krak_grenades			= "G",
	sisters_mandate					= "B",
	sisters_phosphor_grenades		= "G",
	sisters_righteous_fervor		= "F",
	sisters_seal_of_purity			= "B",--
	sisters_witch_hammer			= "X",
	sisters_worship					= "O",--
	sisters_rosarius				= "H",
	sisters_laud_hailer				= "D",
	sisters_angelic_visage			= "B",

	--Entity attack range
	attack					= "A",

}

camera_bindings =
{
	----------------------------------------------------------------------------------------------------------------
	-- CAMERA COMMANDS
	----------------------------------------------------------------------------------------------------------------
	camera_panleft		= "Left,Shift+A",
	camera_panright		= "Right,Shift+D",
	camera_panup		= "Up,Shift+W",
	camera_pandown		= "Down,Shift+S",
	camera_rotate		= "Alt", 
	camera_defaultcam	= "Backspace",
}